using BotSharp.Abstraction.Plugins.Interfaces;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Reflection;
using System.Runtime.Loader;
using System.Text;
using System.Threading.Tasks;

namespace BotSharp.Core.Plugins.lmplements;

/// <summary>
/// Modified from below
/// https://docs.microsoft.com/en-us/dotnet/core/tutorials/creating-app-with-plugin-support
/// This method relies on the HelloWorldPlugin.deps.json and runtimes folder generated by the plugin project,
/// Although the official document does not mention it, it is best to bring HelloWorldPlugin.runtimeconfig.json
/// Plugin project .csproj Other notes, see the document
/// </summary>
public class LazyPluginLoadContext : CollectableAssemblyLoadContext, IPluginContext
{
    private AssemblyDependencyResolver _resolver;

    /// <summary>
    /// Added a recyclable
    /// </summary>
    /// <param name="pluginMainDllFilePath"></param>
    public LazyPluginLoadContext(string pluginId, string pluginMainDllFilePath) 
        : base(name: pluginId)
    {
        _resolver = new AssemblyDependencyResolver(pluginMainDllFilePath);
    }

    protected override Assembly Load(AssemblyName assemblyName)
    {
        // 1. Try searching from this plugin folder first
        string assemblyPath = _resolver.ResolveAssemblyToPath(assemblyName);
        if (assemblyPath != null)
        {
            using (var fs = new FileStream(assemblyPath, FileMode.Open))
            {
                // Using this method, the dll will not be locked
                // Locking the dll will result in: 1. Unable to copy and paste to replace or update 2. Unable to delete
                return LoadFromStream(fs);
            }
        }
        // 2. Try again Search from other enabled plugin folders
        // Tested: You can search below, the assemblyName included in the main program and the assemblyName loaded by the enabled plugin will be located there
        
        var assList = AppDomain.CurrentDomain.GetAssemblies();
        var temp = assList.FirstOrDefault(m => m.GetName().FullName == assemblyName.FullName);
        if (temp != null)
        {
            return temp;
        }
        // Try ignoring the version search
        var temp2 = assList.FirstOrDefault(m => m.GetName().Name == assemblyName.Name);
        if (temp2 != null)
        {
            return temp2;
        }
        // 3. Finally, if the search fails, null is returned, which means that the main program is used. If the last few times are null, an error will be reported.
        // When this plugin is enabled/some types in this plugin are touched, and when the main program does not provide the relevant assemblyName, this method will also be triggered to try to load
        return null;
    }

    protected override IntPtr LoadUnmanagedDll(string unmanagedDllName)
    {
        string libraryPath = _resolver.ResolveUnmanagedDllToPath(unmanagedDllName);
        if (libraryPath != null)
        {
            return LoadUnmanagedDllFromPath(libraryPath);
        }

        return IntPtr.Zero;
    }
}
