using BotSharp.Abstraction.Plugins.Interfaces;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Reflection.Metadata;
using System.Reflection;
using System.Runtime.Loader;
using System.Text;
using System.Threading.Tasks;

namespace BotSharp.Core.Plugins.lmplements;

/// <summary>
/// Modified from below
/// https://docs.microsoft.com/en-us/dotnet/core/tutorials/creating-app-with-plugin-support
/// This method relies on the HelloWorldPlugin.deps.json and runtimes folder generated by the plugin project,
/// Although the official document does not mention it, it is best to bring HelloWorldPlugin.runtimeconfig.json
/// Plugin project .csproj Other notes, see the document
/// </summary>
public class PositivePluginLoadContext : CollectableAssemblyLoadContext, IPluginContext
{
    private AssemblyDependencyResolver _resolver;

    public AssemblyName MainAssemblyName { get; protected set; }

    public IEnumerable<AssemblyName> ReferencedAssemblyNames { get; protected set; }

    /// <summary>
    /// 加了一个可回收
    /// </summary>
    /// <param name="pluginMainDllFilePath"></param>
    public PositivePluginLoadContext(string pluginId, string pluginMainDllFilePath) : base(name: pluginId)
    {
        _resolver = new AssemblyDependencyResolver(pluginMainDllFilePath);

 
        using (var mainFs = new FileStream(pluginMainDllFilePath, FileMode.Open))
        {           
            Assembly mainAssembly = LoadFromStream(mainFs);
            this.MainAssemblyName = mainAssembly.GetName();
            AssemblyName[] referencedAssemblies = mainAssembly.GetReferencedAssemblies();
            this.ReferencedAssemblyNames = referencedAssemblies.AsEnumerable();

            AssemblyFile assemblyFile = new AssemblyFile();

            foreach (var referencedAssembly in referencedAssemblies)
            {
                string assemblyPath = _resolver.ResolveAssemblyToPath(referencedAssembly);
                if (assemblyPath != null)
                {
                    using (var fs = new FileStream(assemblyPath, FileMode.Open))
                    {
                         LoadFromStream(fs);
                    }
                }
            }
        }
    }

    protected override Assembly Load(AssemblyName assemblyName)
    {
        var assList = AppDomain.CurrentDomain.GetAssemblies();
        var temp = assList.FirstOrDefault(m => m.GetName().FullName == assemblyName.FullName);
        if (temp != null)
        {
            return temp;
        }

        return null;
    }

    protected override IntPtr LoadUnmanagedDll(string unmanagedDllName)
    {
        string libraryPath = _resolver.ResolveUnmanagedDllToPath(unmanagedDllName);
        if (libraryPath != null)
        {
            return LoadUnmanagedDllFromPath(libraryPath);
        }

        return IntPtr.Zero;
    }
}